from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np
import tushare as ts

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.infer import (
    build_score_by_date_with_ffill,
    load_offline_scores,
    read_calendar_dates,
    resolve_codes,
    run_trade_simulation,
)


def _expand_paths(raw_paths: list[str]) -> list[str]:
    expanded: list[str] = []
    for raw in raw_paths:
        if any(ch in raw for ch in "*?[]"):
            expanded.extend(str(p) for p in sorted(Path().glob(raw)))
        else:
            expanded.append(raw)
    return expanded


def _resolve_val_dates(calendar_dates: list[str], val_ratio: float, val_embargo_days: int, val_shards: list[str]) -> list[str]:
    if val_shards:
        out: set[str] = set()
        for path in val_shards:
            payload = np.load(path, allow_pickle=True).item()
            if "asof_dates" not in payload:
                raise KeyError(f"missing asof_dates in shard: {path}")
            out.update(str(x) for x in payload["asof_dates"].astype(str).tolist())
        return sorted(out)

    unique_dates = sorted(set(calendar_dates))
    embargo_days = max(0, int(val_embargo_days))
    ratio = float(min(max(val_ratio, 0.0), 0.99))
    usable_for_train_val = len(unique_dates) - embargo_days
    if usable_for_train_val <= 1:
        raise ValueError("insufficient calendar dates for val split")
    val_dates_count = int(round(usable_for_train_val * ratio))
    val_dates_count = max(1, min(usable_for_train_val - 1, val_dates_count))
    train_dates_count = usable_for_train_val - val_dates_count
    return sorted(unique_dates[train_dates_count + embargo_days :])


def main() -> None:
    parser = argparse.ArgumentParser(description="Model backtest runner (offline scores)")
    parser.add_argument("--data-dir", required=True)
    parser.add_argument("--score-dir", required=True, help="offline score dir generated by build_backtest_batches.py")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--topk", type=int, default=20)
    parser.add_argument("--buy-gate", type=float, default=1.0)
    parser.add_argument("--sell-gate", type=float, default=0.5)
    parser.add_argument("--val-ratio", type=float, default=0.15)
    parser.add_argument("--val-embargo-days", type=int, default=30)
    parser.add_argument("--val-shards", nargs="+", default=None)
    parser.add_argument("--ts-token", default="")
    parser.add_argument("--initial-cash", type=float, default=1_000_000.0)
    parser.add_argument("--st-dir", default="", help="directory containing YYYYmmdd_stock_st.parquet files")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    score_dir = Path(args.score_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    calendar_dates = read_calendar_dates(data_dir)
    val_shards = _expand_paths(args.val_shards or [])
    val_dates = _resolve_val_dates(calendar_dates, args.val_ratio, args.val_embargo_days, val_shards)
    if len(val_dates) < 6:
        raise ValueError("validation dates must be >= 6 to backtest until last-5 day")
    asof_dates = val_dates[:-5]

    codes = resolve_codes(data_dir)
    if not codes:
        raise ValueError("no stock folders with required parquet files found")

    score_df = load_offline_scores(score_dir)
    score_by_date = build_score_by_date_with_ffill(asof_dates=asof_dates, codes=codes, score_df=score_df)

    token = args.ts_token or str(os.environ.get("TUSHARE_TOKEN", ""))
    pro = ts.pro_api(token) if token else None

    run_trade_simulation(
        data_dir=data_dir,
        score_by_date=score_by_date,
        asof_dates=asof_dates,
        trading_dates=val_dates[1 : 1 + len(asof_dates)],
        topk=int(args.topk),
        buy_gate=float(args.buy_gate),
        sell_gate=float(args.sell_gate),
        initial_cash=float(args.initial_cash),
        initial_positions={},
        pro=pro,
        st_dir=Path(args.st_dir) if args.st_dir else None,
        out_dir=out_dir,
        verbose=bool(args.verbose),
    )


if __name__ == "__main__":
    main()
